before:
  hooks:
    - go mod download
builds:
  - id: mtail
    main: ./cmd/mtail/main.go
    binary: mtail
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X main.Branch={{.Branch}}
      - -X main.Version={{.Version}}
      - -X main.Revision={{.Commit}}
    gcflags:
      # I love errors.
      - -e
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge'
release:
  github:
  name_template: v{{.Version}}
