# This doesn't work on forked repos per the discussion in
# https://github.com/pascalgn/automerge-action/issues/46 so don't attempt to
# add people other than dependabot to the if field below.
name: automerge
on:
  pull_request_target:
    types:
      - labeled
jobs:
  approve-and-merge-dependabot:
    if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-latest
    steps:

    # Enable auto-merge *before* issuing an approval.
    - name: Enable Github Automerge
      uses: alexwilson/enable-github-automerge-action@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    # We "trust" dependabot updates (this still requires all other checks to pass!)
    - uses: hmarr/auto-approve-action@bca9db08da72b576ae3273e776e7ccf3f0a36e12
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
