name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        if: >-
          github.actor == 'dependabot[bot]'
        uses: octokit/graphql-action@v2.2.20
        with:
          query: |
            mutation enablePullRequestAutoMerge($id: ID!) {
              enablePullRequestAutoMerge(input: {pullRequestId: $id}) {
                clientMutationId
              }
            }
          id: ${{ github.event.pull_request.node_id }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
